
package presentacion;

import javax.swing.DefaultListModel;

public class VentanaMenu extends javax.swing.JFrame {
    private DefaultListModel modeloElemAgregados, modeloElemBorrados;
    

    public VentanaMenu() {
        initComponents();
        modeloElemAgregados=new DefaultListModel();
        modeloElemBorrados=new DefaultListModel();
    }
    
    public void actualizarCantCmbNombres(){
        int cant=cmbNombres.getModel().getSize();
        txtCantItemsAgregados.setText(String.valueOf(cant));
    }
    
    public void actualizarCantlstElemBorrados(){
        int cant=lstElemBorrados.getModel().getSize();
        txtCantItemsBorrados.setText(String.valueOf(cant));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        btnLimpiarPant = new javax.swing.JButton();
        cmbNombres = new javax.swing.JComboBox<>();
        txtElemSeleccionado = new javax.swing.JTextField();
        btnBorrarItem = new javax.swing.JButton();
        btnBorrarTodos = new javax.swing.JButton();
        txtCantItemsBorrados = new javax.swing.JTextField();
        lblElementosBorrados = new javax.swing.JLabel();
        lblElementosAgregados = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCantItemsAgregados = new javax.swing.JTextField();
        lblElemSeleccionado = new javax.swing.JLabel();
        lblListNombes = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstElemAgregados = new javax.swing.JList<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstElemBorrados = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Formulario prueba Jlist y JCombpBox");

        lblNombre.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblNombre.setText("Nombre:");

        txtNombre.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });

        btnAgregar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnLimpiarPant.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnLimpiarPant.setText("Limpiar pantalla");
        btnLimpiarPant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarPantActionPerformed(evt);
            }
        });

        cmbNombres.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        cmbNombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbNombresActionPerformed(evt);
            }
        });

        txtElemSeleccionado.setEditable(false);
        txtElemSeleccionado.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        btnBorrarItem.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnBorrarItem.setText("Borrar Item");
        btnBorrarItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarItemActionPerformed(evt);
            }
        });

        btnBorrarTodos.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnBorrarTodos.setText("Borrar todos los items");
        btnBorrarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarTodosActionPerformed(evt);
            }
        });

        txtCantItemsBorrados.setEditable(false);
        txtCantItemsBorrados.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtCantItemsBorrados.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtCantItemsBorrados.setText("0");

        lblElementosBorrados.setText("Elementos borrados:");

        lblElementosAgregados.setText("Elementos agregados:");

        txtCantItemsAgregados.setEditable(false);
        txtCantItemsAgregados.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtCantItemsAgregados.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtCantItemsAgregados.setText("0");

        lblElemSeleccionado.setText("Elemento seleccionado");

        lblListNombes.setText("Lista de Nombres");

        jScrollPane3.setViewportView(lstElemAgregados);

        jScrollPane1.setViewportView(lstElemBorrados);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblElementosAgregados)
                                .addGap(66, 66, 66)
                                .addComponent(txtCantItemsAgregados, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblElementosBorrados)
                                .addGap(68, 68, 68)
                                .addComponent(txtCantItemsBorrados, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(btnBorrarTodos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(52, 52, 52))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(btnLimpiarPant, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(56, 56, 56)
                                    .addComponent(jLabel3))
                                .addComponent(lblNombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblListNombes, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(173, 173, 173)
                                    .addComponent(lblElemSeleccionado))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(cmbNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtElemSeleccionado, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnBorrarItem, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpiarPant))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblListNombes, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblElemSeleccionado, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(btnBorrarItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbNombres)
                    .addComponent(txtElemSeleccionado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBorrarTodos)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblElementosBorrados)
                        .addComponent(txtCantItemsBorrados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCantItemsAgregados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblElementosAgregados, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        String capturaPantalla=txtNombre.getText().trim();
        if(!capturaPantalla.equals("")){
            cmbNombres.addItem(txtNombre.getText());
            modeloElemAgregados.addElement(txtNombre.getText());
            lstElemAgregados.setModel(modeloElemAgregados);
            txtNombre.setText("");
            actualizarCantCmbNombres();
            cmbNombres.setSelectedIndex(-1);
        }
        txtNombre.requestFocus();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void cmbNombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbNombresActionPerformed
        txtElemSeleccionado.setText((String)cmbNombres.getSelectedItem());
    }//GEN-LAST:event_cmbNombresActionPerformed

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        System.out.println(evt.getKeyCode());
    }//GEN-LAST:event_txtNombreKeyTyped

    private void btnBorrarItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarItemActionPerformed
        int index=cmbNombres.getSelectedIndex();
        if(index>-1){
            String nomBorrdo=(String)cmbNombres.getSelectedItem();
            cmbNombres.removeItemAt(index);
            modeloElemAgregados.remove(index);
            actualizarCantCmbNombres();
            lstElemAgregados.setModel(modeloElemAgregados);
            modeloElemBorrados.addElement(nomBorrdo);
            lstElemBorrados.setModel(modeloElemBorrados);
            actualizarCantlstElemBorrados();
            cmbNombres.setSelectedIndex(-1);
        }
    }//GEN-LAST:event_btnBorrarItemActionPerformed

    private void btnLimpiarPantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarPantActionPerformed
        txtNombre.setText("");
        txtNombre.requestFocus();
    }//GEN-LAST:event_btnLimpiarPantActionPerformed

    private void btnBorrarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarTodosActionPerformed
        int cant=cmbNombres.getModel().getSize();
        String nomBorradoI;
        for(int i=0;i<cant;i++){
            nomBorradoI=cmbNombres.getItemAt(i);
            modeloElemBorrados.addElement(nomBorradoI);
        }
        cmbNombres.removeAllItems();
        modeloElemAgregados.removeAllElements();
        lstElemAgregados.setModel(modeloElemAgregados);
        actualizarCantCmbNombres();
        lstElemBorrados.setModel(modeloElemBorrados);
        actualizarCantlstElemBorrados();
    }//GEN-LAST:event_btnBorrarTodosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBorrarItem;
    private javax.swing.JButton btnBorrarTodos;
    private javax.swing.JButton btnLimpiarPant;
    private javax.swing.JComboBox<String> cmbNombres;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblElemSeleccionado;
    private javax.swing.JLabel lblElementosAgregados;
    private javax.swing.JLabel lblElementosBorrados;
    private javax.swing.JLabel lblListNombes;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JList<String> lstElemAgregados;
    private javax.swing.JList<String> lstElemBorrados;
    private javax.swing.JTextField txtCantItemsAgregados;
    private javax.swing.JTextField txtCantItemsBorrados;
    private javax.swing.JTextField txtElemSeleccionado;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
